COPY ./c:users/kumar/megaman/megaman/Megaman-0.0.1-SNAPSHOT.jar /Users/Kumar/Megaman/Megaman/src/main/java/com/example/rrice/
WORKDIR /Users/Kumar/Megaman/Megaman/src/main/java/com/example/rrice/
EXPOSE 8080
CMD ["java", "-jar", "Megaman-0.0.1-SNAPSHOT.jar"]
